version: "3.9"

services:
  database:
    image: postgres
    container_name: database_aluguel
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aluguel
      - POSTGRES_PASSWORD=aluguel
      - POSTGRES_DB=aluguel
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: aluguel
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local